"""
DeepONet surrogate for Mars thermal FDM forward model.

Replaces expensive FDM simulation (~2s per forward pass, ~33min per inversion)
with a trained neural network (~1ms per forward pass, ~2s per inversion).

Architecture:
    Branch Net: (log_k_upper, log_k_lower, boundary, log_width, latitude) → latent
    Trunk Net:  (sin_Ls, cos_Ls, sin_lt, cos_lt) → latent
    Output:     dot(branch, trunk) + bias → T_surface (K)

Training data is generated by running the numpy FDM forward model
(forward_ebbc_numpy) with random k(z) parameters across the Arcadia
Planitia latitude range.
"""
from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from multiprocessing import Pool, cpu_count
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn

from backend.analysis.thermal_pinn.inversion_real import (
    EBBCConfig,
    forward_ebbc_numpy,
)
from backend.analysis.thermal_pinn.pinn_model import RHO, C_P

logger = logging.getLogger(__name__)

DATA_DIR = Path("backend/data/thermal_pinn")

# ── Configuration ────────────────────────────────────────────────


@dataclass
class DeepONetConfig:
    """Configuration for DeepONet surrogate training and inference."""

    # Training data generation
    n_samples: int = 20000
    query_stride: int = 11  # subsample FDM output: 16032/11 ≈ 1457 query points (MUST be coprime to 24 to sample all local times)
    ice_oversample_frac: float = 0.3  # 30% samples from ice-like regime
    hot_oversample_frac: float = 0.2  # 20% samples from hot-surface regime
    # k(z) parameter sampling ranges (log10 scale for k values)
    k_upper_range: tuple = (-2.5, -0.3)  # log10(W/m/K): 0.003–0.5
    k_lower_range: tuple = (-2.0, 1.0)   # log10(W/m/K): 0.01–10
    boundary_range: tuple = (0.05, 2.5)  # meters
    width_range: tuple = (-2.3, -0.3)    # log10(meters): 0.005–0.5
    latitude_range: tuple = (35.0, 65.0) # degrees N
    albedo_range: tuple = (0.08, 0.35)   # surface albedo (low = hotter peak T)

    # Network architecture
    branch_dim: int = 6   # (log_k_upper, log_k_lower, boundary, log_width, latitude, albedo)
    trunk_dim: int = 4    # (sin_Ls, cos_Ls, sin_lt, cos_lt)
    hidden_dim: int = 256
    latent_dim: int = 128
    n_layers: int = 4

    # Training hyperparameters
    lr: float = 1e-3
    epochs: int = 300
    batch_size: int = 4096
    weight_decay: float = 1e-5

    # FDM config (shared across samples)
    nz: int = 40
    z_max: float = 3.0
    sim_sols: int = 668
    spinup_sols: int = 668
    n_workers: int = 0  # 0 = auto (cpu_count)
# ── Helper functions ─────────────────────────────────────────────


def k_z_from_params(k_upper: float, k_lower: float, boundary: float,
                    width: float, z: np.ndarray) -> np.ndarray:
    """Generate k(z) conductivity profile from parametric model."""
    sigmoid = 1.0 / (1.0 + np.exp(-(z - boundary) / max(width, 1e-6)))
    return k_upper + (k_lower - k_upper) * sigmoid


def encode_trunk(Ls: np.ndarray, lt: np.ndarray) -> np.ndarray:
    """Encode (Ls, local_time) as sin/cos features for periodicity."""
    return np.column_stack([
        np.sin(Ls * 2 * np.pi / 360),
        np.cos(Ls * 2 * np.pi / 360),
        np.sin(lt * 2 * np.pi / 24),
        np.cos(lt * 2 * np.pi / 24),
    ])


# ── Training data generation ────────────────────────────────────


def _generate_one_sample(args):
    """Generate one (k_params → T_surface) training sample."""
    idx, k_upper, k_lower, boundary, width, latitude, albedo, query_indices, fdm_cfg = args
    try:
        cfg = EBBCConfig(
            nz=fdm_cfg["nz"], z_max=fdm_cfg["z_max"],
            sim_sols=fdm_cfg["sim_sols"], spinup_sols=fdm_cfg["spinup_sols"],
            latitude=latitude, Ls_start=0.0, albedo=albedo,
        )
        z = np.linspace(0, cfg.z_max, cfg.nz)
        k_z = k_z_from_params(k_upper, k_lower, boundary, width, z)
        T_surf, _, _, Ls_out, lt_out = forward_ebbc_numpy(k_z, cfg)

        return (
            idx,
            T_surf[query_indices].astype(np.float32),
            Ls_out[query_indices].astype(np.float32),
            lt_out[query_indices].astype(np.float32),
        )
    except Exception as e:
        logger.warning("Sample %d failed: %s", idx, e)
        return idx, None, None, None


def generate_training_data(cfg: DeepONetConfig, seed: int = 42):
    """
    Generate training dataset by running FDM with random k(z) parameters.

    Uses THREE sampling regimes:
      1. Uniform — covers full parameter space
      2. Ice-regime — oversamples ice-like (low k_upper, high k_lower, high lat)
      3. Hot-surface — oversamples low k_upper + low albedo combos that produce
         high daytime T_surf (240-260K), critical for matching real observations

    Returns dict with:
        branch_data: (N, 6) — k_params + latitude + albedo
        query_T: (N, Q) — T_surface at query points
        trunk_enc: (Q, 4) — sin/cos encoded (Ls, local_time)
        query_Ls: (Q,) — raw Ls values
        query_lt: (Q,) — raw local_time values
    """
    rng = np.random.RandomState(seed)

    n_ice = int(cfg.n_samples * cfg.ice_oversample_frac)
    n_hot = int(cfg.n_samples * cfg.hot_oversample_frac)
    n_uniform = cfg.n_samples - n_ice - n_hot

    # ── Uniform sampling (covers full parameter space) ──
    log_k_upper_u = rng.uniform(*cfg.k_upper_range, size=n_uniform)
    log_k_lower_u = rng.uniform(*cfg.k_lower_range, size=n_uniform)
    boundaries_u = rng.uniform(*cfg.boundary_range, size=n_uniform)
    log_widths_u = rng.uniform(*cfg.width_range, size=n_uniform)
    latitudes_u = rng.uniform(*cfg.latitude_range, size=n_uniform)
    albedos_u = rng.uniform(*cfg.albedo_range, size=n_uniform)

    # ── Ice-regime importance sampling ──
    # Low k_upper (insulating regolith), high k_lower (ice), high latitude
    log_k_upper_i = rng.uniform(-2.5, -1.3, size=n_ice)
    log_k_lower_i = rng.uniform(-0.3, 1.0, size=n_ice)
    boundaries_i = rng.uniform(0.05, 1.0, size=n_ice)
    log_widths_i = rng.uniform(-2.3, -0.7, size=n_ice)
    latitudes_i = rng.uniform(48.0, 65.0, size=n_ice)
    albedos_i = rng.uniform(*cfg.albedo_range, size=n_ice)

    # ── Hot-surface importance sampling ──
    # Low k_upper (high daytime peak) + low albedo (absorbs more solar flux)
    # This regime produces T_surf up to 250K at 57N, matching real observations.
    # Without this, training data T_max caps at ~205K and the DeepONet
    # cannot represent the observation range (observations reach 262K).
    log_k_upper_h = rng.uniform(-2.5, -1.3, size=n_hot)  # 0.003-0.05 W/m/K
    log_k_lower_h = rng.uniform(-2.0, 0.0, size=n_hot)   # 0.01-1.0 (includes non-ice)
    boundaries_h = rng.uniform(0.3, 2.5, size=n_hot)     # deeper boundary → more low-k material
    log_widths_h = rng.uniform(-2.3, -0.7, size=n_hot)
    latitudes_h = rng.uniform(*cfg.latitude_range, size=n_hot)  # full range
    albedos_h = rng.uniform(0.08, 0.18, size=n_hot)      # low albedo → hotter surface

    # Concatenate all three regimes
    log_k_upper = np.concatenate([log_k_upper_u, log_k_upper_i, log_k_upper_h])
    log_k_lower = np.concatenate([log_k_lower_u, log_k_lower_i, log_k_lower_h])
    boundaries = np.concatenate([boundaries_u, boundaries_i, boundaries_h])
    log_widths = np.concatenate([log_widths_u, log_widths_i, log_widths_h])
    latitudes = np.concatenate([latitudes_u, latitudes_i, latitudes_h])
    albedos = np.concatenate([albedos_u, albedos_i, albedos_h])

    k_uppers = 10 ** log_k_upper
    k_lowers = 10 ** log_k_lower
    widths = 10 ** log_widths

    logger.info("Sampling: %d uniform + %d ice-regime + %d hot-surface = %d total",
                n_uniform, n_ice, n_hot, cfg.n_samples)

    # Branch data: 6 features (log_k_upper, log_k_lower, boundary, log_width, lat, albedo)
    branch_data = np.column_stack([
        log_k_upper, log_k_lower, boundaries, log_widths, latitudes, albedos,
    ]).astype(np.float32)

    # Query indices (subsample FDM output)
    n_sim_steps = cfg.sim_sols * 24
    query_indices = np.arange(0, n_sim_steps, cfg.query_stride)
    n_query = len(query_indices)
    logger.info("Generating %d samples, %d query points each (stride=%d)",
                cfg.n_samples, n_query, cfg.query_stride)

    # FDM config dict (pickleable for multiprocessing)
    fdm_cfg = {
        "nz": cfg.nz, "z_max": cfg.z_max,
        "sim_sols": cfg.sim_sols, "spinup_sols": cfg.spinup_sols,
    }

    # Build task args (now includes albedo)
    tasks = [
        (i, k_uppers[i], k_lowers[i], boundaries[i], widths[i],
         latitudes[i], albedos[i], query_indices, fdm_cfg)
        for i in range(cfg.n_samples)
    ]
    # Run with multiprocessing
    n_workers = cfg.n_workers if cfg.n_workers > 0 else min(cpu_count(), 20)
    logger.info("Using %d workers for data generation", n_workers)

    query_T = np.zeros((cfg.n_samples, n_query), dtype=np.float32)
    query_Ls = None
    query_lt = None
    n_ok = 0

    t0 = time.time()
    with Pool(n_workers) as pool:
        for result in pool.imap_unordered(_generate_one_sample, tasks):
            idx, T_q, Ls_q, lt_q = result
            if T_q is not None:
                query_T[idx] = T_q
                if query_Ls is None:
                    query_Ls = Ls_q
                    query_lt = lt_q
                n_ok += 1
            if n_ok % 500 == 0 and n_ok > 0:
                elapsed = time.time() - t0
                eta = elapsed / n_ok * (cfg.n_samples - n_ok)
                logger.info("  %d/%d done (%.0fs elapsed, ETA %.0fs)",
                            n_ok, cfg.n_samples, elapsed, eta)

    elapsed = time.time() - t0
    logger.info("Generated %d/%d samples in %.1fs (%.2fs/sample)",
                n_ok, cfg.n_samples, elapsed, elapsed / max(n_ok, 1))

    # Log temperature coverage diagnostics
    T_all = query_T[:n_ok]
    logger.info("  T range: %.1f – %.1f K (need >250K for observation coverage)",
                T_all.min(), T_all.max())
    logger.info("  Samples with T > 240K: %d/%d",
                (T_all.max(axis=1) > 240).sum(), n_ok)
    logger.info("  Samples with T > 250K: %d/%d",
                (T_all.max(axis=1) > 250).sum(), n_ok)

    # Encode trunk
    trunk_enc = encode_trunk(query_Ls, query_lt).astype(np.float32)

    return {
        "branch_data": branch_data[:n_ok],
        "query_T": query_T[:n_ok],
        "trunk_enc": trunk_enc,
        "query_Ls": query_Ls,
        "query_lt": query_lt,
    }


# ── DeepONet Model ───────────────────────────────────────────────


class DeepONet(nn.Module):
    """
    DeepONet for Mars thermal forward model surrogate.

    Learns the operator: (k_params, latitude) × (Ls, local_time) → T_surface
    """

    def __init__(self, branch_dim: int = 5, trunk_dim: int = 4,
                 hidden_dim: int = 128, latent_dim: int = 64, n_layers: int = 3):
        super().__init__()

        # Branch net: k_params → latent embedding
        b_layers = []
        in_dim = branch_dim
        for i in range(n_layers - 1):
            b_layers.extend([nn.Linear(in_dim, hidden_dim), nn.GELU()])
            in_dim = hidden_dim
        b_layers.append(nn.Linear(in_dim, latent_dim))
        self.branch = nn.Sequential(*b_layers)

        # Trunk net: (Ls, lt) encoded → latent embedding
        t_layers = []
        in_dim = trunk_dim
        for i in range(n_layers - 1):
            t_layers.extend([nn.Linear(in_dim, hidden_dim), nn.GELU()])
            in_dim = hidden_dim
        t_layers.append(nn.Linear(in_dim, latent_dim))
        self.trunk = nn.Sequential(*t_layers)

        # Learnable bias
        self.bias = nn.Parameter(torch.zeros(1))

        # Normalization buffers (set during training)
        self.register_buffer("branch_mean", torch.zeros(branch_dim))
        self.register_buffer("branch_std", torch.ones(branch_dim))
        self.register_buffer("T_mean", torch.tensor(180.0))
        self.register_buffer("T_std", torch.tensor(50.0))

    def set_normalization(self, branch_data: np.ndarray, T_data: np.ndarray):
        """Compute and store normalization stats from training data."""
        self.branch_mean = torch.tensor(branch_data.mean(axis=0), dtype=torch.float32)
        self.branch_std = torch.tensor(branch_data.std(axis=0) + 1e-8, dtype=torch.float32)
        self.T_mean = torch.tensor(T_data.mean(), dtype=torch.float32)
        self.T_std = torch.tensor(T_data.std() + 1e-8, dtype=torch.float32)

    def forward(self, branch_input: torch.Tensor, trunk_input: torch.Tensor) -> torch.Tensor:
        """
        Args:
            branch_input: (..., branch_dim) — k_params + latitude
            trunk_input:  (..., trunk_dim) — sin/cos encoded (Ls, lt)

        Returns:
            T_surface: (...,) — predicted surface temperature (K, denormalized)
        """
        # Normalize branch input
        b_norm = (branch_input - self.branch_mean) / self.branch_std
        b_emb = self.branch(b_norm)   # (..., latent_dim)
        t_emb = self.trunk(trunk_input)  # (..., latent_dim)

        # Dot product + bias → normalized T
        T_norm = (b_emb * t_emb).sum(dim=-1) + self.bias

        # Denormalize
        return T_norm * self.T_std + self.T_mean

    def predict_raw(self, branch_input: torch.Tensor,
                    trunk_input: torch.Tensor) -> torch.Tensor:
        """Same as forward but returns normalized output (for training loss)."""
        b_norm = (branch_input - self.branch_mean) / self.branch_std
        b_emb = self.branch(b_norm)
        t_emb = self.trunk(trunk_input)
        return (b_emb * t_emb).sum(dim=-1) + self.bias


# ── Training ─────────────────────────────────────────────────────


class SurrogateDataset(torch.utils.data.Dataset):
    """Flattened (sample, query_point) dataset for DeepONet training."""

    def __init__(self, branch_data: np.ndarray, query_T: np.ndarray,
                 trunk_enc: np.ndarray):
        self.branch = torch.tensor(branch_data, dtype=torch.float32)
        self.T = torch.tensor(query_T, dtype=torch.float32)
        self.trunk = torch.tensor(trunk_enc, dtype=torch.float32)
        self.N = branch_data.shape[0]
        self.Q = trunk_enc.shape[0]

    def __len__(self):
        return self.N * self.Q

    def __getitem__(self, idx):
        i = idx // self.Q  # sample index
        j = idx % self.Q   # query point index
        return self.branch[i], self.trunk[j], self.T[i, j]


def train_deeponet(data: dict, cfg: DeepONetConfig, device: str = "cpu"):
    """
    Train DeepONet on generated (k_params → T_surface) data.

    Returns trained DeepONet model.
    """
    model = DeepONet(
        branch_dim=cfg.branch_dim, trunk_dim=cfg.trunk_dim,
        hidden_dim=cfg.hidden_dim, latent_dim=cfg.latent_dim,
        n_layers=cfg.n_layers,
    ).to(device)

    # Set normalization from data
    model.set_normalization(data["branch_data"], data["query_T"])

    # Normalize targets
    T_mean = data["query_T"].mean()
    T_std = data["query_T"].std() + 1e-8
    query_T_norm = (data["query_T"] - T_mean) / T_std

    dataset = SurrogateDataset(data["branch_data"], query_T_norm, data["trunk_enc"])

    # Use subset sampler for efficiency (don't iterate 1M+ examples every epoch)
    n_total = len(dataset)
    n_per_epoch = min(n_total, 100_000)  # cap at 100k per epoch

    loader = torch.utils.data.DataLoader(
        dataset, batch_size=cfg.batch_size, shuffle=True,
        num_workers=0, pin_memory=False, drop_last=True,
    )

    optimizer = torch.optim.AdamW(model.parameters(), lr=cfg.lr,
                                  weight_decay=cfg.weight_decay)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, cfg.epochs)

    logger.info("Training DeepONet: %d params, %d examples, %d epochs",
                sum(p.numel() for p in model.parameters()),
                n_total, cfg.epochs)

    best_loss = float("inf")
    hist = {"train_loss": []}
    t0 = time.time()

    for epoch in range(cfg.epochs):
        model.train()
        epoch_loss = 0.0
        n_batches = 0

        for batch_branch, batch_trunk, batch_T in loader:
            batch_branch = batch_branch.to(device)
            batch_trunk = batch_trunk.to(device)
            batch_T = batch_T.to(device)

            optimizer.zero_grad()
            T_pred = model.predict_raw(batch_branch, batch_trunk)
            loss = nn.functional.mse_loss(T_pred, batch_T)
            loss.backward()
            optimizer.step()

            epoch_loss += loss.item()
            n_batches += 1

            # Limit batches per epoch for speed
            if n_batches * cfg.batch_size >= n_per_epoch:
                break

        scheduler.step()
        avg_loss = epoch_loss / max(n_batches, 1)
        # Convert normalized MSE to Kelvin
        avg_loss_K = avg_loss * T_std ** 2
        hist["train_loss"].append(avg_loss_K)

        if avg_loss < best_loss:
            best_loss = avg_loss
            best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}

        if (epoch + 1) % 20 == 0 or epoch == 0:
            elapsed = time.time() - t0
            logger.info("Epoch %3d/%d: loss=%.2f K²  (RMS=%.2f K)  lr=%.1e  [%.0fs]",
                        epoch + 1, cfg.epochs, avg_loss_K, avg_loss_K ** 0.5,
                        optimizer.param_groups[0]["lr"], elapsed)

    # Restore best model
    model.load_state_dict(best_state)
    model.eval()

    elapsed = time.time() - t0
    logger.info("Training complete in %.1fs. Best loss: %.2f K² (RMS %.2f K)",
                elapsed, best_loss * T_std ** 2, (best_loss * T_std ** 2) ** 0.5)

    return model, hist


# ── DeepONet Inversion ───────────────────────────────────────────


@dataclass
class InversionResult:
    """Result of DeepONet-based inversion."""
    k_upper: float
    k_lower: float
    boundary: float
    width: float
    TI_upper: float
    TI_lower: float
    loss_final: float
    elapsed: float
    loss_history: list = field(default_factory=list)
    k_upper_history: list = field(default_factory=list)
    k_lower_history: list = field(default_factory=list)
    boundary_history: list = field(default_factory=list)


def run_inversion_deeponet(
    observations: list[dict],
    model: DeepONet,
    latitude: float,
    cfg: DeepONetConfig | None = None,
    n_steps: int = 500,
    lr: float = 0.03,
    albedo_init: float = 0.20,
) -> InversionResult:
    """
    Gradient-based inversion using trained DeepONet surrogate.

    Parameters are constrained to stay within the training distribution
    via sigmoid reparameterization. Albedo is co-optimized as 6th parameter.
    """
    if cfg is None:
        cfg = DeepONetConfig()

    device = next(model.parameters()).device

    # Sigmoid-parameterized learnable variables
    raw_k_upper = torch.tensor(0.0, dtype=torch.float32, requires_grad=True, device=device)
    raw_k_lower = torch.tensor(0.0, dtype=torch.float32, requires_grad=True, device=device)
    raw_boundary = torch.tensor(0.0, dtype=torch.float32, requires_grad=True, device=device)
    raw_width = torch.tensor(0.0, dtype=torch.float32, requires_grad=True, device=device)
    raw_albedo = torch.tensor(0.0, dtype=torch.float32, requires_grad=True, device=device)

    params = [raw_k_upper, raw_k_lower, raw_boundary, raw_width, raw_albedo]
    optimizer = torch.optim.Adam(params, lr=lr)
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=150, gamma=0.5)

    # Ranges
    ku_lo, ku_hi = cfg.k_upper_range
    kl_lo, kl_hi = cfg.k_lower_range
    bd_lo, bd_hi = cfg.boundary_range
    w_lo, w_hi = cfg.width_range
    al_lo, al_hi = cfg.albedo_range

    def to_physical(raw_ku, raw_kl, raw_bd, raw_w, raw_al):
        log_ku = ku_lo + (ku_hi - ku_lo) * torch.sigmoid(raw_ku)
        log_kl = kl_lo + (kl_hi - kl_lo) * torch.sigmoid(raw_kl)
        bd = bd_lo + (bd_hi - bd_lo) * torch.sigmoid(raw_bd)
        log_w = w_lo + (w_hi - w_lo) * torch.sigmoid(raw_w)
        albedo = al_lo + (al_hi - al_lo) * torch.sigmoid(raw_al)
        return log_ku, log_kl, bd, log_w, albedo

    # Trunk inputs (fixed)
    trunk_data = []
    for obs in observations:
        Ls = obs["solar_lon"]
        lt = obs["local_time"]
        trunk_data.append([
            np.sin(Ls * 2 * np.pi / 360),
            np.cos(Ls * 2 * np.pi / 360),
            np.sin(lt * 2 * np.pi / 24),
            np.cos(lt * 2 * np.pi / 24),
        ])
    trunk_input = torch.tensor(trunk_data, dtype=torch.float32, device=device)
    T_obs = torch.tensor([obs["bt_kelvin"] for obs in observations],
                         dtype=torch.float32, device=device)
    n_obs = len(observations)

    lat_tensor = torch.tensor(latitude, dtype=torch.float32, device=device)

    result = InversionResult(0, 0, 0, 0, 0, 0, 0, 0)
    t0 = time.time()

    for step in range(n_steps):
        optimizer.zero_grad()

        log_ku, log_kl, boundary, log_w, albedo = to_physical(
            raw_k_upper, raw_k_lower, raw_boundary, raw_width, raw_albedo)

        # Branch: (log_ku, log_kl, boundary, log_w, latitude, albedo)
        branch_single = torch.stack([log_ku, log_kl, boundary, log_w,
                                      lat_tensor, albedo])
        branch_input = branch_single.unsqueeze(0).expand(n_obs, -1)

        T_pred = model(branch_input, trunk_input)

        loss = ((T_pred - T_obs) ** 2).mean()
        loss.backward()
        optimizer.step()
        scheduler.step()

        with torch.no_grad():
            ku_val = 10 ** log_ku.item()
            kl_val = 10 ** log_kl.item()
            bd_val = boundary.item()
            w_val = 10 ** log_w.item()
            al_val = albedo.item()

        result.loss_history.append(loss.item())
        result.k_upper_history.append(ku_val)
        result.k_lower_history.append(kl_val)
        result.boundary_history.append(bd_val)

        if (step + 1) % 50 == 0 or step == 0:
            logger.info(
                "Step %3d: loss=%.2f K²  k_u=%.4f k_l=%.4f bd=%.3fm al=%.3f",
                step + 1, loss.item(), ku_val, kl_val, bd_val, al_val,
            )

    elapsed = time.time() - t0

    with torch.no_grad():
        log_ku, log_kl, boundary, log_w, albedo_final = to_physical(
            raw_k_upper, raw_k_lower, raw_boundary, raw_width, raw_albedo)
        ku_val = 10 ** log_ku.item()
        kl_val = 10 ** log_kl.item()
        bd_val = boundary.item()
        w_val = 10 ** log_w.item()

    result.k_upper = ku_val
    result.k_lower = kl_val
    result.boundary = bd_val
    result.width = w_val
    result.TI_upper = np.sqrt(ku_val * RHO * C_P)
    result.TI_lower = np.sqrt(kl_val * RHO * C_P)
    result.loss_final = result.loss_history[-1]
    result.elapsed = elapsed

    logger.info("DeepONet inversion done in %.2fs (%d steps)", elapsed, n_steps)
    logger.info("  k_upper=%.5f (TI=%.0f), k_lower=%.4f (TI=%.0f), boundary=%.3fm, albedo=%.3f",
                result.k_upper, result.TI_upper, result.k_lower, result.TI_lower,
                result.boundary, albedo_final.item())

    return result
